JordyHandmade/Areas/Admin/ViewModels/Town/TownSelectViewModel.cs
namespace JordyHandmade.Web.Areas.Admin.ViewModels.Town
{
    using JordyHandmade.Web.ViewModels.Town;

    public class TownSelectViewModel
    {
        public int Id { get; set; }

        public IEnumerable<TownFormModel>? Towns { get; set; }
    }
}

JordyHandmade/Areas/Admin/Controllers/TownController.cs
namespace JordyHandmade.Web.Areas.Admin.Controllers
{    
    using Microsoft.AspNetCore.Mvc;

    using JordyHandmade.Services.Data.Interfaces;
    using JordyHandmade.Web.Infrastructure.Extensions;
    using JordyHandmade.Web.ViewModels.Town;
    using JordyHandmade.Web.Areas.Admin.ViewModels.Town;
    using static JordyHandmade.Common.NotificationMessagesConstants;

    public class TownController : BaseAdminController
    {
        private readonly ITownService townService;

        public TownController(ITownService townService)
        {
            this.townService = townService;
        }

        public async Task<IActionResult> AllForSelect()
        {
            TownSelectViewModel selectModel = new TownSelectViewModel()
            {
                Towns = await townService.GetAllForSelectAsync()
            };

            return View(selectModel);
        }

        [HttpPost]
        public IActionResult AllForSelect(TownSelectViewModel selectModel)
        {
            return RedirectToAction("Change", new { selectModel.Id });
        }

        public async Task<IActionResult> Change(int id)
        {
            TownFormModel changeModel = await townService.GetTownByIdAsync(id);

            return View(changeModel);
        }

        public IActionResult Add()
        {
            TownFormModel inputModel = new TownFormModel();

            return View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(TownFormModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            bool townExists = await townService.TownExistsByZipAsync(inputModel.ZipCode);

            if (townExists)
            {
                //TempData[ErrorMessage] = "A town with this Zip code already exists!";
                ModelState.AddModelError(nameof(inputModel.ZipCode), "A town with this Zip code already exists!");
                return View(inputModel);
            }

            try
            {
                await townService.AddTownAsync(inputModel);
            }
            catch (Exception)
            {
                this.TempData[ErrorMessage] = "Unexpected error occurred while adding the new town!" +
                    "Please try again later.";

                return View(inputModel);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (User.IsAdmin() == false)
            {
                return Unauthorized();
            }
            try
            {
                TownFormModel editModel = await townService.GetTownByIdAsync(id);
                return View(editModel);
            }
            catch (Exception)
            {
                return BadRequest();
            }

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TownFormModel editModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editModel);
            }

            try
            {
                await townService.UpdateAsync(id, editModel);
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Unexpected error occurred while editing selected town!");
                return View(editModel);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            try
            {
                TownFormModel formModel = await townService.GetTownByIdAsync(id);
                return View(formModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, TownFormModel formModel)
        {
            if (User.IsAdmin() == false)
            {
                return Unauthorized();
            }

            try
            {
                await townService.DeleteAsync(id);
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Unexpected error occurred while deleting this town!");
                return View(formModel);
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

JordyHandmade/Areas/Admin/Views/Town/Add.cshtml
@model TownFormModel

@{
    ViewData["Title"] = "Add town";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
    <div class="card w-100">        
        <div class="card-body">
            <h3 class="card-title text-center">Please enter city name and zip code</h3>            
            <form asp-controller="Town" asp-action="Add">
                <div class="mb-3">
                    <label asp-for="TownName" class="form-label">Town name</label>
                    <input asp-for="TownName" class="form-control" aria-required="true" />
                    <span asp-validation-for="TownName" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for="ZipCode" class="form-label">Zip code</label>
                    <input asp-for="ZipCode" class="form-control" aria-required="true" />
                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <input class="btn btn-primary" type="submit" value="Add" />
                </div>
            </form>

        </div>

        <a asp-controller="Home" asp-action="Index" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Back to Admin Page</a>

    </div>
</div> 

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

JordyHandmade/Areas/Admin/Views/Town/AllForSelect.cshtml
@model TownSelectViewModel

@{
    ViewData["Title"] = "All towns";
}

<h2 class="text-center">@ViewData["Title"] for administration</h2>
<hr />

<div class="text-center">
    <p>If you would like to add new town please use this section</p>
</div>
<div class="text-center">     
    <a asp-area="Admin" asp-controller="Town" asp-action="Add" class="btn btn-success mb-2 w-40 p-3 fw-bold">Add new town</a>      
</div>

<hr />

<div class="text-center">
    <p>If you would like to edit or delete existing town please select the town to be changed from the list below. 
    Keep in mind that deleting a town will also delete all addresses associated with it.</p>
</div>

<div>
    <form asp-action="AllForSelect" method="post">
        <div class="mb-3">
            <label asp-for="@Model.Id" class="form-label-add-edit">Select town</label>
            <select asp-for="@Model.Id" class="form-control" aria-required="true">
            @foreach (var town in Model.Towns!)
            {                            
                <option value="@town.Id">@town.TownName @town.ZipCode</option>
            }
            </select>
            <span asp-validation-for="@Model.Id" class="text-danger"></span>
        </div>      
        <div class="mb-3">
            <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Select" />
        </div>        
    </form>        
</div>

JordyHandmade/Areas/Admin/Views/Town/Change.cshtml
@model TownFormModel

@{
	ViewData["Title"] = "Town changes";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />


<div class="d-flex justify-content-center">
	<div class="card " style="width: 50rem;">
		<div class="card-body">
			<p class="card-text"><span class="fw-bold">You selected the following town for changing:</span></p>
			<h3 class="card-title text-center">@Model.TownName @Model.ZipCode</h3>
		</div>
		<div class="mb-3 d-flex justify-content-center flex-column">			
			<a asp-area="Admin" asp-controller="Town" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Edit</a>
			<a asp-area="Admin" asp-controller="Town" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger btn-lg">Delete</a>
			<p>Again! Keep in mind that deleting a town will also delete all addresses associated with it!</p>
		</div>
	</div>
</div>

JordyHandmade/Areas/Admin/Views/Town/Delete.cshtml
@model TownFormModel

@{
	ViewData["Title"] = "Delete Town";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<form asp-action="Delete">
	<div class="d-flex justify-content-center">
		<div class="card " style="width: 50rem;">
			<div class="card-body">
				<p class="card-text"><span class="fw-bold">Are sure you want to delete this town:</span></p>
				<h3 class="card-title text-center">@Model.TownName @Model.ZipCode</h3>				
			</div>
			<div class="mb-3 d-flex justify-content-center flex-column">
				<input type="submit" value="Delete" class="btn btn-danger" />
				<a asp-area="Admin" asp-controller="Home" asp-action="Index" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Back to Admin Page</a>
			</div>
		</div>
	</div>
</form>

JordyHandmade/Areas/Admin/Views/Town/Edit.cshtml
@model TownFormModel

@{
    ViewData["Title"] = "Edit town";
}

<h2 class="text-center">@ViewData["Title"]</h2>
<hr />

<div class="row">
<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
    <form asp-action="Edit" method="post">
        <div class="mb-3">
            <label asp-for="@Model.TownName" class="form-label-add-edit">Town name</label>
            <input asp-for="@Model.TownName" class="form-control" aria-required="true" />
            <span asp-validation-for="@Model.TownName" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="@Model.ZipCode" class="form-label-add-edit">Zip Code</label>
            <input asp-for="@Model.ZipCode" class="form-control" aria-required="true" />
            <span asp-validation-for="@Model.ZipCode" class="text-danger"></span>
        </div>       
        <div class="mb-3">
            <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Edit" />
        </div>
    </form>
</div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}